apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    {{- include "cardgame-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cardgame-core.name" . }}-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cardgame-core.name" . }}-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}-proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxy.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.pullPolicy }}
          ports:
            - containerPort: 8082
          env:
            - name: "RABBITMQ_URI"
              valueFrom:
                secretKeyRef:
                  key:  rabbitmq_uri
                  name: {{ .Release.Name }}-uri
