apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-queries
  labels:
    {{- include "cardgame-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cardgame-core.name" . }}-queries
      app.kubernetes.io/instance: {{ .Release.Name }}-queries
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cardgame-core.name" . }}-queries
        app.kubernetes.io/instance: {{ .Release.Name }}-queries
    spec:
      containers:
        - name: queries
          image: "{{ .Values.queries.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.queries.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: "MONGO_URI"
              valueFrom:
                secretKeyRef:
                  key:  mongo_uri
                  name: {{ .Release.Name }}-uri
            - name: "RABBITMQ_URI"
              valueFrom:
                secretKeyRef:
                  key:  rabbitmq_uri
                  name: {{ .Release.Name }}-uri

