apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: raul-cardgame
  region: us-east-1

iam:
  withOIDC: true   
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
vpc:
  subnets:
    private:
      us-east-1c: { id: subnet-0064cbb5bf2086a41}
      us-east-1d: { id: subnet-0ce1127dbee4ada19 }
      us-east-1b: { id: subnet-07f280948e955088d }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 3
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.large
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
