apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardgame-master
  labels:
    app: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-master
      app.kubernetes.io/instance: cardgame-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-master
        app.kubernetes.io/instance: cardgame-master
    spec:
      containers:
        - name: master
          image: "316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-master"
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              port: 8085
              path: /actuator
          env:
            - name: "MONGO_URI"
              valueFrom:
                secretKeyRef:
                  key:  mongo_uri
                  name: cardgame-uri

