server:
  port: 8082
  origin: ${ORIGIN:*}
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: game-proxy
  sleuth:
    sampler:
      percentage: 1.0
  zipkin: # All zipkin features disabled for integration tests
    enabled: false
microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.proxyhandles}
  routingKey: ${ROUTING_KEY:cardgame.#}
  uriBus: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}